### ISSUE TITLE
.netkan file needs to reflect incompatibility with parallax 2.0

### ISSUE THREAD

**Issue by Qazerowl** [KSP-RO/RealSolarSystem#275]
The RSS package on CKAN recommends parallax, but parallax version 2 is the default version. the .netkan file in this repo needs to be updated to reflect the incompatibility with parallax =< 2.0, so that an older version is installed by default.

**Comment by NathanKell** [comment]
I do not believe this can be done for mere recommends, only depends, but @HebaruSan may know for sure.

**Comment by HebaruSan** [comment]
I think this would make it pull in the right version when installing:

```yaml
recommends:
  - name: Parallax
    max_version: 1.3.1
```

But then the user would be able to upgrade afterwards. This might be better:

```yaml
conflicts:
  - name: Parallax
    min_version: 2.0.0
```
